#!/bin/sh
# Generates THIRD-PARTY-NOTICES: the license text of every module that links
# into the dnsrtt binary on any released platform.  Run from the repo root;
# goreleaser runs it as a before hook so release archives always carry
# up-to-date notices.
set -eu

out="THIRD-PARTY-NOTICES"

# Union of linked modules across all released platforms, since some deps are
# platform-specific (e.g. mousetrap is Windows-only).
mods=$(for os in linux darwin freebsd windows; do
	GOOS=$os go list -deps -f '{{if not .Standard}}{{.Module.Path}}{{end}}' .
done | sort -u | grep -v '^github.com/farrokhi/dnsrtt$')

{
	echo "Third-party license notices for dnsrtt"
	echo
	echo "The dnsrtt binary statically links the Go modules below.  Each module"
	echo "remains under its own license, reproduced here in full."
	echo "Generated by scripts/gen-third-party-notices.sh; do not edit by hand."

	for m in $mods; do
		dir=$(go list -m -f '{{.Dir}}' "$m")
		ver=$(go list -m -f '{{.Version}}' "$m")
		files=$(find "$dir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) | sort)

		if [ -z "$files" ]; then
			echo "error: no license file found for $m" >&2
			exit 1
		fi

		echo
		echo "--------------------------------------------------------------------"
		echo "$m $ver"
		echo "--------------------------------------------------------------------"
		for f in $files; do
			echo
			cat "$f"
		done
	done
} >"$out"

echo "wrote $out"
